app:
  name: Config App
  description: Learing new thing about spring boot and microservice by building ${app.name}

my:
  greeting: Hello Kind people
  list:
    value: fruit,vegetable,water

dbIncredent: "{connectionString: 'http://localhost:8090', userName:'xaxa', password:'xoxo'}"

db:
  connection: "{connectionString: 'http://localhost:8085', userName:'toto', password:'tata'}"
  host: 127.0.0.1
  port: 1600


management.endpoints.web.exposure.include: "*"