app:
  name: Config App TEST
  description: TESTLearing new thing about spring boot and microservice by building ${app.name}

my:
  greeting: Hello Kind people TEST
  list:
    value: fruit,vegetable,water

dbIncredent: "{connectionString: 'http://localhost:8090', userName:'xaxa', password:'xoxo'}"

db:
  connection: "{connectionString: 'http://localhost:8082', userName:'toto', password:'tata'}"
  host: 124.0.0.1
  port: 2000


management.endpoints.web.exposure.include: "*"