app:
  name: Config App TEST
  description: TESTLearing new thing about spring boot and microservice by building ${app.name}

my:
  greeting: Hello Kind people TEST
  list:
    value: fruit,vegetable,water

dbIncredent: "{connectionString: 'http://localhost:8070', userName:'yaya', password:'yoyo'}"

db:
  connection: "{connectionString: 'http://localhost:8192', userName:'wowo', password:'wawa'}"
  host: 120.0.0.1
  port: 2000


management.endpoints.web.exposure.include: "*"